version: '3'

services:
  web_ui:
    build: ./web_ui
    ports:
    - "80:80"
  node:
    build: ./node
    depends_on:
    - postgres_db
    ports:
      - "8080:80"
  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

secrets:
  database_user:
    file: db_user.txt
  database_name:
    file: db_name.txt
  database_password:
    file: db_password.txt