version: '3'

services:
  web_ui:
    build: ./web_ui
    ports:
    - "80:80"
  node:
    build: ./node
    depends_on:
    - postgres_db
    ports:
      - "8080:80"
  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: